export const countries = [
    { key: 'US', label: 'Amerika Birleşik Devletleri', flag: '🇺🇸' },
    { key: 'AS', label: 'Amerika Samoa', flag: '🇦🇸' },
    { key: 'AD', label: 'Andorra', flag: '🇦🇩' },
    { key: 'AO', label: 'Angola', flag: '🇦🇴' },
    { key: 'AI', label: 'Anguilla', flag: '🇦🇮' },
    { key: 'AQ', label: 'Antarktika', flag: '🇦🇶' },
    { key: 'AG', label: 'Antigua ve Barbuda', flag: '🇦🇬' },
    { key: 'AR', label: 'Arjantin', flag: '🇦🇷' },
    { key: 'AL', label: 'Arnavutluk', flag: '🇦🇱' },
    { key: 'AW', label: 'Aruba', flag: '🇦🇼' },
    { key: 'AU', label: 'Avustralya', flag: '🇦🇺' },
    { key: 'AT', label: 'Avusturya', flag: '🇦🇹' },
    { key: 'AZ', label: 'Azerbaycan', flag: '🇦🇿' },
    { key: 'BS', label: 'Bahama', flag: '🇧🇸' },
    { key: 'BH', label: 'Bahreyn', flag: '🇧🇭' },
    { key: 'BD', label: 'Bangladeş', flag: '🇧🇩' },
    { key: 'BB', label: 'Barbados', flag: '🇧🇧' },
    { key: 'EH', label: 'Batı Sahara', flag: '🇪🇭' },
    { key: 'BE', label: 'Belçika', flag: '🇧🇪' },
    { key: 'BZ', label: 'Belize', flag: '🇧🇿' },
    { key: 'BJ', label: 'Benin', flag: '🇧🇯' },
    { key: 'BM', label: 'Bermuda', flag: '🇧🇲' },
    { key: 'BY', label: 'Beyaz Rusya', flag: '🇧🇾' },
    { key: 'AE', label: 'Birleşik Arap Emirlikleri', flag: '🇦🇪' },
    { key: 'GB', label: 'Birleşik Krallık', flag: '🇬🇧' },
    { key: 'BO', label: 'Bolivya', flag: '🇧🇴' },
    { key: 'BQ', label: 'Bonaire, Sint Eustatius ve Saba', flag: '🇧🇶' },
    { key: 'BA', label: 'Bosna-Hersek', flag: '🇧🇦' },
    { key: 'BW', label: 'Botsvana', flag: '🇧🇼' },
    { key: 'BV', label: 'Bouvet Adası', flag: '🇧🇻' },
    { key: 'BR', label: 'Brezilya', flag: '🇧🇷' },
    { key: 'IO', label: 'Britanya Hırvatistan Denizi', flag: '🇮🇴' },
    { key: 'BN', label: 'Brunei', flag: '🇧🇳' },
    { key: 'BG', label: 'Bulgaristan', flag: '🇧🇬' },
    { key: 'BF', label: 'Burkina Faso', flag: '🇧🇫' },
    { key: 'BI', label: 'Burundi', flag: '🇧🇮' },
    { key: 'CV', label: 'Cape Verde', flag: '🇨🇻' },
    { key: 'KY', label: 'Cayman Adaları', flag: '🇰🇾' },
    { key: 'DZ', label: 'Cezayir', flag: '🇩🇿' },
    { key: 'CX', label: 'Christmas Adası', flag: '🇨🇽' },
    { key: 'CC', label: 'Cocos (Keeling) Adaları', flag: '🇨🇨' },
    { key: 'DJ', label: 'Djibouti', flag: '🇩🇯' },
    { key: 'DM', label: 'Dominika', flag: '🇩🇲' },
    { key: 'DO', label: 'Dominik Cumhuriyeti', flag: '🇩🇴' },
    { key: 'EC', label: 'Ekvador', flag: '🇪🇨' },
    { key: 'GQ', label: 'Ekvator Ginesi', flag: '🇬🇶' },
    { key: 'SV', label: 'El Salvador', flag: '🇸🇻' },
    { key: 'ID', label: 'Endonezya', flag: '🇮🇩' },
    { key: 'ER', label: 'Eritrea', flag: '🇪🇷' },
    { key: 'AM', label: 'Ermenistan', flag: '🇦🇲' },
    { key: 'EE', label: 'Estonya', flag: '🇪🇪' },
    { key: 'SZ', label: 'Eswatini', flag: '🇸🇿' },
    { key: 'ET', label: 'Etiyopya', flag: '🇪🇹' },
    { key: 'FK', label: 'Falkland Adaları', flag: '🇫🇰' },
    { key: 'FO', label: 'Faroe Adaları', flag: '🇫🇴' },
    { key: 'MA', label: 'Fas', flag: '🇲🇦' },
    { key: 'FJ', label: 'Fiji', flag: '🇫🇯' },
    { key: 'PH', label: 'Filipinler', flag: '🇵🇭' },
    { key: 'FI', label: 'Finlandiya', flag: '🇫🇮' },
    { key: 'PS', label: 'Filistin', flag: '🇵🇸' },
    { key: 'FR', label: 'Fransa', flag: '🇫🇷' },
    { key: 'PF', label: 'Fransız Polinezyası', flag: '🇵🇫' },
    { key: 'GA', label: 'Gabon', flag: '🇬🇦' },
    { key: 'GM', label: 'Gambiya', flag: '🇬🇲' },
    { key: 'GH', label: 'Gana', flag: '🇬🇭' },
    { key: 'GI', label: 'Gibraltar', flag: '🇬🇮' },
    { key: 'GN', label: 'Gine', flag: '🇬🇳' },
    { key: 'GW', label: 'Gine-Bissau', flag: '🇬🇼' },
    { key: 'GD', label: 'Grenada', flag: '🇬🇩' },
    { key: 'GL', label: 'Grönland', flag: '🇬🇱' },
    { key: 'GP', label: 'Guadeloupe', flag: '🇬🇵' },
    { key: 'GU', label: 'Guam', flag: '🇬🇺' },
    { key: 'GT', label: 'Guatemala', flag: '🇬🇹' },
    { key: 'GG', label: 'Guernsey', flag: '🇬🇬' },
    { key: 'GY', label: 'Guyana', flag: '🇬🇾' },
    { key: 'ZA', label: 'Güney Afrika', flag: '🇿🇦' },
    { key: 'GS', label: 'Güney Georgia', flag: '🇬🇸' },
    { key: 'KR', label: 'Güney Kore', flag: '🇰🇷' },
    { key: 'SS', label: 'Güney Sudan', flag: '🇸🇸' },
    { key: 'GE', label: 'Gürcistan', flag: '🇬🇪' },
    { key: 'HT', label: 'Haiti', flag: '🇭🇹' },
    { key: 'IN', label: 'Hindistan', flag: '🇮🇳' },
    { key: 'NL', label: 'Hollanda', flag: '🇳🇱' },
    { key: 'HN', label: 'Honduras', flag: '🇭🇳' },
    { key: 'HK', label: 'Hong Kong', flag: '🇭🇰' },
    { key: 'IQ', label: 'Irak', flag: '🇮🇶' },
    { key: 'IR', label: 'İran', flag: '🇮🇷' },
    { key: 'IE', label: 'İrlanda', flag: '🇮🇪' },
    { key: 'ES', label: 'İspanya', flag: '🇪🇸' },
    { key: 'IL', label: 'İsrail', flag: '🇮🇱' },
    { key: 'SE', label: 'İsveç', flag: '🇸🇪' },
    { key: 'CH', label: 'İsviçre', flag: '🇨🇭' },
    { key: 'IT', label: 'İtalya', flag: '🇮🇹' },
    { key: 'IS', label: 'İzlanda', flag: '🇮🇸' },
    { key: 'JM', label: 'Jamaika', flag: '🇯🇲' },
    { key: 'JP', label: 'Japonya', flag: '🇯🇵' },
    { key: 'JE', label: 'Jersey', flag: '🇯🇪' },
    { key: 'JO', label: 'Ürdün', flag: '🇯🇴' },
    { key: 'ME', label: 'Karadağ', flag: '🇲🇪' },
    { key: 'KZ', label: 'Kazakistan', flag: '🇰🇿' },
    { key: 'KE', label: 'Kenya', flag: '🇰🇪' },
    { key: 'KI', label: 'Kiribati', flag: '🇰🇮' },
    { key: 'CO', label: 'Kolombiya', flag: '🇨🇴' },
    { key: 'KM', label: 'Komorlar', flag: '🇰🇲' },
    { key: 'CG', label: 'Kongo', flag: '🇨🇬' },
    { key: 'CD', label: 'Kongo (DRK)', flag: '🇨🇩' },
    { key: 'CR', label: 'Kosta Rika', flag: '🇨🇷' },
    { key: 'KP', label: 'Kuzey Kore', flag: '🇰🇵' },
    { key: 'MP', label: 'Kuzey Mariana Adaları', flag: '🇲🇵' },
    { key: 'CU', label: 'Küba', flag: '🇨🇺' },
    { key: 'KW', label: 'Kuveyt', flag: '🇰🇼' },
    { key: 'CY', label: 'Kıbrıs', flag: '🇨🇾' },
    { key: 'KG', label: 'Kırgızistan', flag: '🇰🇬' },
    { key: 'LA', label: 'Laos', flag: '🇱🇦' },
    { key: 'LS', label: 'Lesotho', flag: '🇱🇸' },
    { key: 'LV', label: 'Letonya', flag: '🇱🇻' },
    { key: 'LR', label: 'Liberya', flag: '🇱🇷' },
    { key: 'LY', label: 'Libya', flag: '🇱🇾' },
    { key: 'LI', label: 'Liechtenstein', flag: '🇱🇮' },
    { key: 'LT', label: 'Litvanya', flag: '🇱🇹' },
    { key: 'LB', label: 'Lübnan', flag: '🇱🇧' },
    { key: 'LU', label: 'Lüksemburg', flag: '🇱🇺' },
    { key: 'HU', label: 'Macaristan', flag: '🇭🇺' },
    { key: 'MG', label: 'Madagaskar', flag: '🇲🇬' },
    { key: 'MK', label: 'Makedonya', flag: '🇲🇰' },
    { key: 'MW', label: 'Malavi', flag: '🇲🇼' },
    { key: 'MV', label: 'Maldivler', flag: '🇲🇻' },
    { key: 'MY', label: 'Malezya', flag: '🇲🇾' },
    { key: 'ML', label: 'Mali', flag: '🇲🇱' },
    { key: 'MT', label: 'Malta', flag: '🇲🇹' },
    { key: 'IM', label: 'Man Adası', flag: '🇮🇲' },
    { key: 'MH', label: 'Marşal Adaları', flag: '🇲🇭' },
    { key: 'MQ', label: 'Martinique', flag: '🇲🇶' },
    { key: 'MU', label: 'Mauritius', flag: '🇲🇺' },
    { key: 'YT', label: 'Mayotte', flag: '🇾🇹' },
    { key: 'MX', label: 'Meksika', flag: '🇲🇽' },
    { key: 'FM', label: 'Mikronezya', flag: '🇫🇲' },
    { key: 'MD', label: 'Moldova', flag: '🇲🇩' },
    { key: 'MC', label: 'Monaco', flag: '🇲🇨' },
    { key: 'MN', label: 'Moğolistan', flag: '🇲🇳' },
    { key: 'MS', label: 'Montserrat', flag: '🇲🇸' },
    { key: 'MR', label: 'Moritanya', flag: '🇲🇷' },
    { key: 'MZ', label: 'Mozambik', flag: '🇲🇿' },
    { key: 'MM', label: 'Myanmar', flag: '🇲🇲' },
    { key: 'EG', label: 'Mısır', flag: '🇪🇬' },
    { key: 'NA', label: 'Namibya', flag: '🇳🇦' },
    { key: 'NR', label: 'Nauru', flag: '🇳🇷' },
    { key: 'NP', label: 'Nepal', flag: '🇳🇵' },
    { key: 'NE', label: 'Nijer', flag: '🇳🇪' },
    { key: 'NG', label: 'Nijerya', flag: '🇳🇬' },
    { key: 'NI', label: 'Nikaragua', flag: '🇳🇮' },
    { key: 'NU', label: 'Niue', flag: '🇳🇺' },
    { key: 'NF', label: 'Norfolk Adası', flag: '🇳🇫' },
    { key: 'NO', label: 'Norveç', flag: '🇳🇴' },
    { key: 'CF', label: 'Orta Afrika Cumhuriyeti', flag: '🇨🇫' },
    { key: 'UZ', label: 'Özbekistan', flag: '🇺🇿' },
    { key: 'OM', label: 'Umman', flag: '🇴🇲' },
    { key: 'PK', label: 'Pakistan', flag: '🇵🇰' },
    { key: 'PW', label: 'Palau', flag: '🇵🇼' },
    { key: 'PA', label: 'Panama', flag: '🇵🇦' },
    { key: 'PG', label: 'Papua Yeni Gine', flag: '🇵🇬' },
    { key: 'PY', label: 'Paraguay', flag: '🇵🇾' },
    { key: 'PE', label: 'Peru', flag: '🇵🇪' },
    { key: 'PN', label: 'Pitcairn Adaları', flag: '🇵🇳' },
    { key: 'PL', label: 'Polonya', flag: '🇵🇱' },
    { key: 'PT', label: 'Portekiz', flag: '🇵🇹' },
    { key: 'PR', label: 'Porto Riko', flag: '🇵🇷' },
    { key: 'RE', label: 'Reunion', flag: '🇷🇪' },
    { key: 'RO', label: 'Romanya', flag: '🇷🇴' },
    { key: 'RU', label: 'Rusya', flag: '🇷🇺' },
    { key: 'RW', label: 'Ruanda', flag: '🇷🇼' },
    { key: 'SM', label: 'San Marino', flag: '🇸🇲' },
    { key: 'ST', label: 'Sao Tome ve Principe', flag: '🇸🇹' },
    { key: 'SN', label: 'Senegal', flag: '🇸🇳' },
    { key: 'SC', label: 'Seyşeller', flag: '🇸🇨' },
    { key: 'SL', label: 'Sierra Leone', flag: '🇸🇱' },
    { key: 'SG', label: 'Singapur', flag: '🇸🇬' },
    { key: 'SK', label: 'Slovakya', flag: '🇸🇰' },
    { key: 'SI', label: 'Slovenya', flag: '🇸🇮' },
    { key: 'SB', label: 'Solomon Adaları', flag: '🇸🇧' },
    { key: 'SO', label: 'Somali', flag: '🇸🇴' },
    { key: 'LK', label: 'Sri Lanka', flag: '🇱🇰' },
    { key: 'SD', label: 'Sudan', flag: '🇸🇩' },
    { key: 'SR', label: 'Surinam', flag: '🇸🇷' },
    { key: 'SY', label: 'Suriye', flag: '🇸🇾' },
    { key: 'SA', label: 'Suudi Arabistan', flag: '🇸🇦' },
    { key: 'SJ', label: 'Svalbard ve Jan Mayen', flag: '🇸🇯' },
    { key: 'RS', label: 'Sırbistan', flag: '🇷🇸' },
    { key: 'TJ', label: 'Tacikistan', flag: '🇹🇯' },
    { key: 'TZ', label: 'Tanzanya', flag: '🇹🇿' },
    { key: 'TH', label: 'Tayland', flag: '🇹🇭' },
    { key: 'TW', label: 'Tayvan', flag: '🇹🇼' },
    { key: 'TG', label: 'Togo', flag: '🇹🇬' },
    { key: 'TK', label: 'Tokelau', flag: '🇹🇰' },
    { key: 'TO', label: 'Tonga', flag: '🇹🇴' },
    { key: 'TT', label: 'Trinidad ve Tobago', flag: '🇹🇹' },
    { key: 'TN', label: 'Tunus', flag: '🇹🇳' },
    { key: 'TC', label: 'Turks ve Caicos Adaları', flag: '🇹🇨' },
    { key: 'TV', label: 'Tuvalu', flag: '🇹🇻' },
    { key: 'TR', label: 'Türkiye', flag: '🇹🇷' },
    { key: 'TM', label: 'Türkmenistan', flag: '🇹🇲' },
    { key: 'UG', label: 'Uganda', flag: '🇺🇬' },
    { key: 'UA', label: 'Ukrayna', flag: '🇺🇦' },
    { key: 'UY', label: 'Uruguay', flag: '🇺🇾' },
    { key: 'VU', label: 'Vanuatu', flag: '🇻🇺' },
    { key: 'VA', label: 'Vatikan', flag: '🇻🇦' },
    { key: 'VE', label: 'Venezuela', flag: '🇻🇪' },
    { key: 'VN', label: 'Vietnam', flag: '🇻🇳' },
    { key: 'WF', label: 'Wallis ve Futuna', flag: '🇼🇫' },
    { key: 'YE', label: 'Yemen', flag: '🇾🇪' },
    { key: 'NC', label: 'Yeni Kaledonya', flag: '🇳🇨' },
    { key: 'NZ', label: 'Yeni Zelanda', flag: '🇳🇿' },
    { key: 'GR', label: 'Yunanistan', flag: '🇬🇷' },
    { key: 'ZM', label: 'Zambiya', flag: '🇿🇲' },
    { key: 'ZW', label: 'Zimbabve', flag: '🇿🇼' },
];