export type Currency = {
    country: string;
    currency: string;
    symbol: string;
    flag: any;
}

const receiverCurrencies = [
    {
        country: 'Almanya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/de.png'),
    },
    {
        country: 'Andorra',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ad.png'),
    },
    {
        country: 'Arnavutluk',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/al.png'),
    },
    {
        country: 'Avusturya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/at.png'),
    },
    {
        country: 'Azerbaycan',
        currency: 'AZN',
        symbol: '₼',
        flag: require('../assets/images/flags/az.png'),
    },
    {
        country: 'Belçika',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/be.png'),
    },
    {
        country: 'Belarus',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/by.png'),
    },
    {
        country: 'Bosna-Hersek',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ba.png'),
    },
    {
        country: 'Bulgaristan',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/bg.png'),
    },
    {
        country: 'Bulgaristan',
        currency: 'BGN',
        symbol: 'лв',
        flag: require('../assets/images/flags/bg.png'),
    },
    {
        country: 'Çek Cumhuriyeti',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/cz.png'),
    },
    {
        country: 'Danimarka',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/dk.png'),
    },
    {
        country: 'Estonya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ee.png'),
    },
    {
        country: 'Finlandiya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/fi.png'),
    },
    {
        country: 'Fransa',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/fr.png'),
    },
    {
        country: 'Gürcistan',
        currency: 'GEL',
        symbol: '₾',
        flag: require('../assets/images/flags/ge.png'),
    },
    {
        country: 'Hindistan',
        currency: 'INR',
        symbol: '₹',
        flag: require('../assets/images/flags/in.png'),
    },
    {
        country: 'Hırvatistan',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/hr.png'),
    },
    {
        country: 'Hollanda',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/nl.png'),
    },
    {
        country: 'İngiltere',
        currency: 'GBP',
        symbol: '£',
        flag: require('../assets/images/flags/gb.png'),
    },
    {
        country: 'İspanya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/es.png'),
    },
    {
        country: 'İsveç',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/se.png'),
    },
    {
        country: 'İsviçre',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ch.png'),
    },
    {
        country: 'İtalya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/it.png'),
    },
    {
        country: 'İzlanda',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/is.png'),
    },
    {
        country: 'Karadağ',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/me.png'),
    },
    {
        country: 'Kazakistan',
        currency: 'KZT',
        symbol: '₸',
        flag: require('../assets/images/flags/kz.png'),
    },
    {
        country: 'Letonya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/lv.png'),
    },
    {
        country: 'Lihtenştayn',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/li.png'),
    },
    {
        country: 'Litvanya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/lt.png'),
    },
    {
        country: 'Lüksemburg',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/lu.png'),
    },
    {
        country: 'Macaristan',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/hu.png'),
    },
    {
        country: 'Malta',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/mt.png'),
    },
    {
        country: 'Moldova',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/md.png'),
    },
    {
        country: 'Moldova',
        currency: 'MDL',
        symbol: '₽',
        flag: require('../assets/images/flags/md.png'),
    },
    {
        country: 'Monako',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/mc.png'),
    },
    {
        country: 'Norveç',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/no.png'),
    },
    {
        country: 'Pakistan',
        currency: 'PKR',
        symbol: '₨',
        flag: require('../assets/images/flags/pk.png'),
    },
    {
        country: 'Polonya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/pl.png'),
    },
    {
        country: 'Polonya',
        currency: 'PLN',
        symbol: 'zł',
        flag: require('../assets/images/flags/pl.png'),
    },
    {
        country: 'Portekiz',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/pt.png'),
    },
    {
        country: 'Romanya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ro.png'),
    },
    {
        country: 'Romanya',
        currency: 'RON',
        symbol: 'lei',
        flag: require('../assets/images/flags/ro.png'),
    },
    {
        country: 'Rusya',
        currency: 'RUB',
        symbol: '₽',
        flag: require('../assets/images/flags/ru.png'),
    },
    {
        country: 'Sırbistan',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/rs.png'),
    },
    {
        country: 'Slovakya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/sk.png'),
    },
    {
        country: 'Slovenya',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/si.png'),
    },
    {
        country: 'Tacikistan',
        currency: 'TJS',
        symbol: 'SM',
        flag: require('../assets/images/flags/tj.png'),
    },
    {
        country: 'Türkiye',
        currency: 'TRY',
        symbol: '₺',
        flag: require('../assets/images/flags/tr.png'),
    },
    {
        country: 'Türkiye',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/tr.png'),
    },
    {
        country: 'Türkiye',
        currency: 'GBP',
        symbol: '£',
        flag: require('../assets/images/flags/tr.png'),
    },
    {
        country: 'Türkmenistan',
        currency: 'TMT',
        symbol: 'm',
        flag: require('../assets/images/flags/tm.png'),
    },
    {
        country: 'Ukrayna',
        currency: 'UAH',
        symbol: '₴',
        flag: require('../assets/images/flags/ua.png'),
    },
    {
        country: 'Ukrayna',
        currency: 'USD',
        symbol: '$',
        flag: require('../assets/images/flags/ua.png'),
    },
    {
        country: 'Ukrayna',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/ua.png'),
    },
    {
        country: 'Ukrayna',
        currency: 'GBP',
        symbol: '£',
        flag: require('../assets/images/flags/gb.png'),
    },
    {
        country: 'Yunanistan',
        currency: 'EUR',
        symbol: '€',
        flag: require('../assets/images/flags/gr.png'),
    },
];

export default receiverCurrencies;